### PR TITLE
Added typescript def. file.

### PR DESCRIPTION
**Pull request by soerenbf**
Using the library in a typescript react project, and would love simple typings to expose the intended use of the components.

### CODE REVIEW

**Comment by trevorr** [comment]
Thanks for suggesting this. I needed to make some style changes from your PR, but I've included TS definitions in the latest release, 1.0.2.

**Comment by DonGissel** [comment]
Since PR #2 and #3 have been closed and not merged, you should probably acknowledge the contributions of the authors elsewhere..? 🤔

**Comment by trevorr** [comment]
This PR is acknowledged in the commit: https://github.com/trevorr/react-scroll-manager/commit/de313da724639b7c879308fdc472376f741fecfa

**Comment by trevorr** [comment]
Also in the README.md:

> Thanks to Anders Gissel for suggesting a fix for IE 11 window scrolling and Søren Bruus Frank for submitting TypeScript definitions.

**Pull request closed without merging**
